### PR TITLE
Pe 351/cec

### PR DESCRIPTION
**Pull request by lherlein**
Added `sendcec` command that hits the new sendCecX endpoint. 

Work for https://brightsign.atlassian.net/browse/PE-351

Note - new command will only work on players with the new version of supervisor.

### CODE REVIEW

**Review by mingjun7 — APPROVED** [review]
LGTM and I've tried on my player.

**Review by bhastings1019 — APPROVED** [review]
Looks good. Giving approval so it's not blocked by approvals. 

1/ add acknowledgement in the code that this feature is for experimental usage
2/ @mingjun7 @lherlein please coordinate to test this against the custom supervisor, actually sending 36 to send <STANDBY> and 0d to send <Text View On>.

**Review by jdmedlin1 — APPROVED** [review]
LGTM

**Comment by lherlein** [comment]
@bhastings1019 acknowledgement added in the command description. Mingjun and I both tested against our individual players, but having a legit test framework would be fantastic!

**Pull request merged**
